(deftheme dodgey-light-soap-theme
  "Created 2015-03-11.")

(custom-theme-set-variables
 'dodgey-light-soap-theme
 '(ansi-color-faces-vector [default default default italic underline success warning error])
 '(ansi-color-names-vector ["#2e3436" "#a40000" "#4e9a06" "#c4a000" "#204a87" "#5c3566" "#729fcf" "#eeeeec"])
 '(blink-cursor-delay 1.5)
 '(company-c-headers-path-system (quote ("/usr/include/" "/usr/local/include/" "/usr/include/c++/4.6/")))
 '(company-c-headers-path-user (quote ("/home/dodge/workspace")))
 '(company-minimum-prefix-length 2)
 '(company-tooltip-margin 2)
 '(custom-safe-themes (quote ("422662ca327aec391aaee6e36836af1a489e44b2ead0ad6ad5f22775fa2b0c06" "930a202ae41cb4417a89bc3a6f969ebb7fcea5ffa9df6e7313df4f7a2a631434" "b8c99a002227c98b796605d479bcca6fe71c1c20f22fe68fb9d65b91a9373563" "c87cc60d01cf755375759d165c1d60d9586c6a31f0b5437a0378c2a93cfc8407" default)))
 '(package-selected-packages (quote (company-c-headers company-irony zygospore yasnippet ws-butler volatile-highlights undo-tree smartparens light-soap-theme iedit helm-swoop helm-projectile helm-gtags helm-company guide-key golden-ratio ggtags function-args flycheck duplicate-thing dtrt-indent dash-functional dash-at-point comment-dwim-2 clean-aindent-mode anzu))))

(custom-theme-set-faces
 'dodgey-light-soap-theme
 '(button ((t (:inherit link))))
 '(company-preview ((t (:background "saddle brown" :foreground "wheat"))))
 '(company-preview-common ((t (:inherit company-preview :foreground "navajo white"))))
 '(company-scrollbar-bg ((t (:inherit company-tooltip :background "goldenrod"))))
 '(company-scrollbar-fg ((t (:background "dark red"))))
 '(company-tooltip ((t (:background "saddle brown" :foreground "navajo white"))))
 '(company-tooltip-annotation ((t (:inherit company-tooltip :foreground "black"))))
 '(company-tooltip-mouse ((t (:inherit highlight :background "gray42"))))
 '(company-tooltip-search ((t (:inherit company-tooltip-selection))))
 '(cursor ((((class color) (min-colors 89)) (:background "#cdcdaf"))))
 '(helm-M-x-key ((t (:foreground "red3" :underline t))))
 '(helm-candidate-number ((t (:background "salmon2" :foreground "black"))))
 '(helm-selection ((t (:background "goldenrod"))))
 '(mode-line ((((class color) (min-colors 89)) (:box (:line-width 1 :color nil :style released-button) :bold t :foreground "#6f6f6f" :background "#e4e3c1"))))
 '(mode-line-buffer-id ((((class color) (min-colors 89)) (:bold t :foreground "#545454" :background nil))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:box (:line-width 1 :color nil :style pressed-button) :foreground "#545454" :background "#fafad4"))))
 '(region ((((class color) (min-colors 89)) (:background "#616161" :foreground "#e4e3c1"))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#365f71"))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "#a1a1a1"))))
 '(font-lock-negation-char-face ((((class color) (min-colors 89)) (:foreground "#794732"))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "#794732"))))
 '(font-lock-doc-face ((((class color) (min-colors 89)) (:foreground "#a1a1a1"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "#86546c" :bold t))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:bold ((class color) (min-colors 89)) :foreground "#4f4b78"))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "#355d3e"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "#5a532d"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "#5f3041"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:foreground "#f70f2a" :background "#e4e3c1"))))
 '(highlight ((((class color) (min-colors 89)) (:foreground "#616161" :background "#cdcdaf"))))
 '(fringe ((((class color) (min-colors 89)) (:background "#e4e3c1" :foreground "#6f6f6f"))))
 '(isearch ((((class color) (min-colors 89)) (:bold t :foreground "#f70f2a" :background "#cdcdaf"))))
 '(mode-line-highlight ((((class color) (min-colors 89)) (:background "#b8b89c"))))
 '(vertical-border ((((class color) (min-colors 89)) (:foreground "#616161"))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:bold t :foreground "#4f4b78"))))
 '(link ((((class color) (min-colors 89)) (:foreground "#794732" :underline t))))
 '(org-code ((((class color) (min-colors 89)) (:foreground "#545454"))))
 '(org-hide ((((class color) (min-colors 89)) (:foreground "#6f6f6f"))))
 '(org-level-1 ((((class color) (min-colors 89)) (:bold t :foreground "#545454" :height 1.1))))
 '(org-level-2 ((((class color) (min-colors 89)) (:bold nil :foreground "#616161"))))
 '(org-level-3 ((((class color) (min-colors 89)) (:bold t :foreground "#6f6f6f"))))
 '(org-level-4 ((((class color) (min-colors 89)) (:bold nil :foreground "#b8b89c"))))
 '(org-date ((((class color) (min-colors 89)) (:underline t :foreground "#5f3041"))))
 '(org-footnote ((((class color) (min-colors 89)) (:underline t :foreground "#6f6f6f"))))
 '(org-link ((((class color) (min-colors 89)) (:underline t :foreground "#5a532d"))))
 '(org-special-keyword ((((class color) (min-colors 89)) (:foreground "#86546c"))))
 '(org-verbatim ((((class color) (min-colors 89)) (:foreground "#6f6f6f"))))
 '(org-block ((((class color) (min-colors 89)) (:foreground "#616161"))))
 '(org-quote ((((class color) (min-colors 89)) (:inherit org-block :slant italic))))
 '(org-verse ((((class color) (min-colors 89)) (:inherit org-block :slant italic))))
 '(org-todo ((((class color) (min-colors 89)) :foreground "#4f4b78" :bold t)))
 '(org-done ((((class color) (min-colors 89)) (:bold t :foreground "#b8b89c"))))
 '(org-warning ((((class color) (min-colors 89)) (:underline t :foreground "#f70f2a"))))
 '(org-agenda-structure ((((class color) (min-colors 89)) (:weight bold :foreground "#616161" :box (:color "#6f6f6f") :background "#cdcdaf"))))
 '(org-agenda-date ((((class color) (min-colors 89)) (:foreground "#5f3041" :height 1.1))))
 '(org-agenda-date-weekend ((((class color) (min-colors 89)) (:weight normal :foreground "#6f6f6f"))))
 '(org-agenda-date-today ((((class color) (min-colors 89)) (:weight bold :foreground "#4f4b78" :height 1.4))))
 '(org-scheduled ((((class color) (min-colors 89)) (:foreground "#5a532d"))))
 '(org-ellipsis ((((class color) (min-colors 89)) (:foreground "#365f71"))))
 '(org-document-info-keyword ((((class color) (min-colors 89)) (:foreground "#86546c"))))
 '(org-sexp-date ((((class color) (min-colors 89)) (:foreground "#6f6f6f"))))
 '(ffap ((((class color) (min-colors 89)) (:foreground "#6f6f6f"))))
 '(warning ((((class color) (min-colors 89)) (:foreground "#f70f2a"))))
 '(undo-tree-visualizer-current-face ((((class color) (min-colors 89)) :foreground "#365f71")))
 '(undo-tree-visualizer-register-face ((((class color) (min-colors 89)) :foreground "#5a532d")))
 '(undo-tree-visualizer-default-face ((((class color) (min-colors 89)) :foreground "#545454")))
 '(undo-tree-visualizer-unmodified-face ((((class color) (min-colors 89)) :foreground "#5f3041")))
 '(trailing-whitespace ((((class color) (min-colors 89)) :foreground nil :background "#f70f2a")))
 '(default ((((class color) (min-colors 89)) (:background "#fafad4" :foreground "#474747")))))

(provide-theme 'dodgey-light-soap-theme)
