;; Keep track of loading time
(defconst emacs-start-time (current-time))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;; PRE-LOAD APPEARANCE SETTINGS ;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; These are here, and not in config.org, because they should be present
; during the loading and saving of config.el (generated by babel). Also,
; if any code in the early parts of config.org fails, the basic appearance
; of emacs will be preserved.

;; Load wilson theme:

(load "~/.emacs.d/wilson-theme.el")

;; Setup default window size:
(add-to-list 'default-frame-alist '(height . 40))
(add-to-list 'default-frame-alist '(width . 160))

;; Get rid of annoying stuff:
(setq gc-cons-threshold 100000000)
(setq inhibit-startup-message t)

;; Use 'y' instead of "yes" and 'n' instead of "no" at prompt.
(defalias 'yes-or-no-p 'y-or-n-p)

;; Save point position between sessions:
(require 'saveplace)
(setq-default save-place t)
(setq save-place-file (expand-file-name ".places" user-emacs-directory))

;; No splash screen:
(setq inhibit-startup-screen t)

;; Set font:
;(add-to-list 'default-frame-alist
;         '(font .  "Ubuntu Mono-12"))
;(set-face-attribute 'default t :font  "Ubuntu Mono-12")

;; Get rid of UI clutter:

; disables tool bar
(tool-bar-mode -1)
; disables pmenu bar, can re-enable as a popub with 'C-mouse-3'
(menu-bar-mode -99)
; no scroll bar please
(toggle-scroll-bar -1)

;; Dont truncate lines:
(toggle-truncate-lines)
(global-set-key (kbd "C-c ; t") 'toggle-truncate-lines)

;; I prefer a non-blinking cursor:
(blink-cursor-mode 0)

;; Highlight current line:
(global-hl-line-mode 1)
(set-face-background 'hl-line "#3b3b3b")
(set-face-foreground 'highlight nil)

;; Set up mode line:
;; display time in mode line
(display-time-mode t)

;; Dont ask me if I want to use these features before I do:
(put 'narrow-to-region 'disabled nil)
(put 'scroll-left 'disabled nil)


;;;;;;;; Load config.org and save its elisp to config.el ;;;;;;;;;;

(require 'org)
(org-babel-load-file
 (expand-file-name "config.org"
                   user-emacs-directory))
