(deftheme jazzy-dodge
  "Created 2015-03-03.")

(custom-theme-set-variables
 'jazzy-dodge
 '(ansi-color-faces-vector [default default default italic underline success warning error])
 '(ansi-color-names-vector ["#151515" "#953331" "#546a29" "#909737" "#385e6b" "#7f355e" "#34676f" "#c6a57b"])
 '(blink-cursor-delay 1.5)
 '(company-minimum-prefix-length 2)
 '(company-tooltip-margin 2)
 '(blink-cursor-mode t)
 '(custom-safe-themes (quote ("b0aac20ae39a48fa2386e57698d55e84845c763666f6fa8763d90232c6c862ae" "789844278c5a75283b5015c1fc7bebe7e4cf97843b8f8cffe21fafa05e81e90a" "c87cc60d01cf755375759d165c1d60d9586c6a31f0b5437a0378c2a93cfc8407" default))))

(custom-theme-set-faces
 'jazzy-dodge
 '(company-preview ((t (:background "saddle brown" :foreground "wheat"))))
 '(company-preview-common ((t (:inherit company-preview :foreground "navajo white"))))
 '(company-scrollbar-bg ((t (:inherit company-tooltip :background "goldenrod"))))
 '(company-scrollbar-fg ((t (:background "dark red"))))
 '(company-tooltip ((t (:background "saddle brown" :foreground "navajo white"))))
 '(company-tooltip-annotation ((t (:inherit company-tooltip :foreground "black"))))
 '(company-tooltip-mouse ((t (:inherit highlight :background "gray42"))))
 '(company-tooltip-search ((t (:inherit company-tooltip-selection))))
 '(cursor ((((class color) (min-colors 89)) (:foreground "#c6a57b" :background "#c6a57b"))))
 '(button ((t (:underline t))))
 '(link ((((class color) (min-colors 89)) (:foreground "#909737" :underline t :weight bold))))
 '(link-visited ((((class color) (min-colors 89)) (:foreground "#909737" :underline t :weight normal))))
 '(fringe ((((class color) (min-colors 89)) (:foreground "#303030" :background "#151515"))))
 '(header-line ((((class color) (min-colors 89)) (:foreground "#909737" :background "#101010" :box (:line-width -1 :color "#151515" :style released-button)))))
 '(highlight ((((class color) (min-colors 89)) (:background "#202020"))))
 '(compilation-info ((((class color) (min-colors 89)) (:foreground "#7e9960" :underline t))))
 '(compilation-line-number ((((class color) (min-colors 89)) (:foreground "#909737"))))
 '(match ((((class color) (min-colors 89)) (:background "#101010" :foreground "#ba5b34" :weight bold))))
 '(isearch ((((class color) (min-colors 89)) (:foreground "#909737" :background "#101010"))))
 '(isearch-fail ((((class color) (min-colors 89)) (:foreground "#c6a57b" :background "#953331"))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:foreground "#909737" :background "#505050"))))
 '(menu ((((class color) (min-colors 89)) (:foreground "#c6a57b" :background "#151515"))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "#385e6b"))))
 '(mode-line ((((class color) (min-colors 89)) (:foreground "#c6a57b" :background "#202020" :box (:line-width 5 :color "#202020")))))
 '(mode-line-buffer-id ((((class color) (min-colors 89)) (:foreground "#909737" :weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 89)) (:inverse-video t))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:inherit mode-line :foreground "#546a29" :background "#101010" :box (:line-width 5 :color "#101010")))))
 '(region ((((class color) (min-colors 89)) (:background "#c6a57b" :foreground "#385e6b"))))
 '(secondary-selection ((((class color) (min-colors 89)) (:background "#505050"))))
 '(trailing-whitespace ((((class color) (min-colors 89)) (:background "#953331"))))
 '(vertical-border ((((class color) (min-colors 89)) (:foreground "#c6a57b"))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#385e6b"))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "#505050"))))
 '(font-lock-comment-delimiter-face ((((class color) (min-colors 89)) (:foreground "#505050"))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "#7f355e"))))
 '(font-lock-doc-face ((((class color) (min-colors 89)) (:foreground "#7e9960"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "#385e6b"))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:foreground "#909737"))))
 '(font-lock-negation-char-face ((((class color) (min-colors 89)) (:foreground "#c6a57b"))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 89)) (:foreground "#385e6b"))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "#953331"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "#909737"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "#ba5b34"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:foreground "#909737" :weight bold :underline t))))
 '(c-annotation-face ((((class color) (min-colors 89)) (:inherit font-lock-constant-face))))
 '(diff-added ((((class color) (min-colors 89)) (:foreground "#7e9960"))))
 '(diff-changed ((((class color) (min-colors 89)) (:foreground "#909737"))))
 '(diff-removed ((((class color) (min-colors 89)) (:foreground "#953331"))))
 '(diff-header ((((class color) (min-colors 89)) (:background "#202020"))))
 '(diff-file-header ((((class color) (min-colors 89)) (:background "#505050" :foreground "#c6a57b" :bold t))))
 '(flycheck-error ((((supports :underline (:style wave))) (:underline (:style wave :color "#953331") :inherit unspecified :foreground unspecified :background unspecified)) (t (:foreground "#953331" :weight bold :underline t))))
 '(flycheck-fringe-error ((((class color) (min-colors 89)) (:foreground "#953331" :background "#151515"))))
 '(flycheck-warning ((((supports :underline (:style wave))) (:underline (:style wave :color "#ba5b34") :inherit unspecified :foreground unspecified :background unspecified)) (t (:foreground "#ba5b34" :weight bold :underline t))))
 '(flycheck-fringe-warning ((((class color) (min-colors 89)) (:foreground "#ba5b34" :background "#151515"))))
 '(helm-header ((((class color) (min-colors 89)) (:foreground "#546a29" :background "#151515" :underline nil :box nil))))
 '(helm-source-header ((((class color) (min-colors 89)) (:foreground "#909737" :background "#101010" :weight bold :box (:line-width -1 :style released-button)))))
 '(helm-selection ((((class color) (min-colors 89)) (:background "#101010"))))
 '(helm-selection-line ((((class color) (min-colors 89)) (:background "#101010"))))
 '(helm-visible-mark ((((class color) (min-colors 89)) (:foreground "#151515" :background "#909737"))))
 '(helm-candidate-number ((((class color) (min-colors 89)) (:foreground "#7e9960" :background "#101010"))))
 '(linum ((((class color) (min-colors 89)) (:foreground "#505050" :background "#101010"))))
 '(org-agenda-date-today ((((class color) (min-colors 89)) (:foreground "white" :slant italic :weight bold))))
 '(org-agenda-structure ((((class color) (min-colors 89)) (:inherit font-lock-comment-face))))
 '(org-archived ((((class color) (min-colors 89)) (:foreground "#c6a57b" :weight bold))))
 '(org-checkbox ((((class color) (min-colors 89)) (:background "#505050" :foreground "white" :box (:line-width 1 :style released-button)))))
 '(org-date ((((class color) (min-colors 89)) (:foreground "#385e6b" :underline t))))
 '(org-done ((((class color) (min-colors 89)) (:bold t :weight bold :foreground "#7e9960"))))
 '(org-formula ((((class color) (min-colors 89)) (:foreground "#909737"))))
 '(org-headline-done ((((class color) (min-colors 89)) (:foreground "#7e9960"))))
 '(org-hide ((((class color) (min-colors 89)) (:foreground "#101010"))))
 '(org-level-1 ((((class color) (min-colors 89)) (:foreground "#ba5b34"))))
 '(org-level-2 ((((class color) (min-colors 89)) (:foreground "#7e9960"))))
 '(org-level-3 ((((class color) (min-colors 89)) (:foreground "#385e6b"))))
 '(org-level-4 ((((class color) (min-colors 89)) (:foreground "#909737"))))
 '(org-level-5 ((((class color) (min-colors 89)) (:foreground "#34676f"))))
 '(org-level-6 ((((class color) (min-colors 89)) (:foreground "#546a29"))))
 '(org-level-7 ((((class color) (min-colors 89)) (:foreground "#953331"))))
 '(org-level-8 ((((class color) (min-colors 89)) (:foreground "#385e6b"))))
 '(org-link ((((class color) (min-colors 89)) (:foreground "#909737" :underline t))))
 '(org-scheduled ((((class color) (min-colors 89)) (:foreground "#7e9960"))))
 '(org-scheduled-previously ((((class color) (min-colors 89)) (:foreground "#953331"))))
 '(org-scheduled-today ((((class color) (min-colors 89)) (:foreground "#5c737c"))))
 '(org-special-keyword ((((class color) (min-colors 89)) (:foreground "#909737"))))
 '(org-table ((((class color) (min-colors 89)) (:foreground "#7e9960"))))
 '(org-tag ((((class color) (min-colors 89)) (:bold t :weight bold))))
 '(org-time-grid ((((class color) (min-colors 89)) (:foreground "#ba5b34"))))
 '(org-todo ((((class color) (min-colors 89)) (:bold t :foreground "#953331" :weight bold))))
 '(org-upcoming-deadline ((((class color) (min-colors 89)) (:inherit font-lock-keyword-face))))
 '(org-warning ((((class color) (min-colors 89)) (:bold t :foreground "#953331" :weight bold))))
 '(outline-8 ((((class color) (min-colors 89)) (:inherit default))))
 '(outline-7 ((((class color) (min-colors 89)) (:inherit outline-8 :height 1.0))))
 '(outline-6 ((((class color) (min-colors 89)) (:inherit outline-7 :height 1.0))))
 '(outline-5 ((((class color) (min-colors 89)) (:inherit outline-6 :height 1.0))))
 '(outline-4 ((((class color) (min-colors 89)) (:inherit outline-5 :height 1.0))))
 '(outline-3 ((((class color) (min-colors 89)) (:inherit outline-4 :height 1.0))))
 '(outline-2 ((((class color) (min-colors 89)) (:inherit outline-3 :height 1.0))))
 '(outline-1 ((((class color) (min-colors 89)) (:inherit outline-2 :height 1.0))))
 '(show-paren-mismatch ((((class color) (min-colors 89)) (:foreground "#953331" :background "#151515" :weight bold))))
 '(show-paren-match ((((class color) (min-colors 89)) (:foreground "#385e6b" :background "#151515" :weight bold))))
 '(undo-tree-visualizer-active-branch-face ((((class color) (min-colors 89)) (:foreground "#385e6b"))))
 '(undo-tree-visualizer-current-face ((((class color) (min-colors 89)) (:foreground "#953331" :weight bold))))
 '(undo-tree-visualizer-default-face ((((class color) (min-colors 89)) (:foreground "#c6a57b"))))
 '(undo-tree-visualizer-register-face ((((class color) (min-colors 89)) (:foreground "#909737"))))
 '(undo-tree-visualizer-unmodified-face ((((class color) (min-colors 89)) (:foreground "#c6a57b"))))
 '(which-func ((((class color) (min-colors 89)) (:foreground "#7e9960"))))
 '(default ((((class color) (min-colors 89)) (:foreground "#c6a57b" :background "#151515")))))

(provide-theme 'jazzy-dodge)
